tasks:
  - init: |
      yarn install
      curl -fsSL https://deno.land/x/install/install.sh | sh
      sudo ln -s /home/gitpod/.deno/bin/deno /bin/deno
      cd deno && deno cache src/main.ts && cd ..

vscode:
  extensions: 
   - denoland.vscode-deno
