{
 "title": "OpenAI trace metrics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "rootspan",
    "label": "Root Span",
    "query": {
     "query": "label_values(traces_spanmetrics_latency_bucket,span_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Latency of $rootspan",
   "type": "stat",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "traces_spanmetrics_latency_sum{source=\"tempo\", span_name=\"$rootspan\"} / traces_spanmetrics_latency_count{source=\"tempo\", span_name=\"$rootspan\"}",
     "legendFormat": "Average"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(traces_spanmetrics_latency_bucket{source=\"tempo\", span_name=\"$rootspan\"}[$__rate_interval])))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Average Duration of all spans",
   "type": "stat",
   "gridPos": { "h": 9, "w": 17, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "traces_spanmetrics_latency_sum{source=\"tempo\"} / traces_spanmetrics_latency_count",
     "legendFormat": "{{span_name}}"
    }
   ]
  },
  {
   "title": "Percentiles",
   "type": "timeseries",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, span_name) (rate(traces_spanmetrics_latency_bucket[$__rate_interval])))",
     "legendFormat": "{{span_name}} p99"
    },
    {
     "expr": "traces_spanmetrics_latency_sum{source=\"tempo\"} / traces_spanmetrics_latency_count",
     "legendFormat": "{{span_name}} avg"
    }
   ]
  }
 ]
}