name: ci

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

jobs:
  starter-vite-tsc:
    strategy:
      matrix:
        node-version: [16, 18, 20]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - run: pnpm install
        working-directory: starter-vite-tsc
      - run: pnpm tsc
        working-directory: starter-vite-tsc
      - run: pnpm build
        working-directory: starter-vite-tsc
